import { spawn } from "node:child_process";
import { readFile, unlink, readdir } from "node:fs/promises";
import * as path from "node:path";
import * as os from "node:os";

/* ─────────────────────────────────────────────
   Types
   ───────────────────────────────────────────── */

export interface TranscriptSegment {
  text: string;
  start: number;
  duration: number;
}

/* ─────────────────────────────────────────────
   Main entry point — multi-strategy transcript fetch
   ───────────────────────────────────────────── */

/**
 * Fetch transcript for a YouTube video using the best available strategy.
 * Tries yt-dlp first (most reliable for auto-generated captions across languages),
 * then falls back to youtranscript.com and finally YouTube page scraping.
 */
export async function fetchTranscript(
  videoId: string
): Promise<TranscriptSegment[]> {
  // Strategy 1: yt-dlp with android client (best for auto-generated captions)
  try {
    return await fetchViaYtDlp(videoId, true);
  } catch (err) {
    console.log("[transcript] yt-dlp android failed:", (err as Error).message);
  }

  // Strategy 2: yt-dlp with default client
  try {
    return await fetchViaYtDlp(videoId, false);
  } catch (err) {
    console.log("[transcript] yt-dlp default failed:", (err as Error).message);
  }

  // Strategy 3: youtranscript.com API (lightweight HTTP API)
  try {
    return await fetchViaYouTranscript(videoId);
  } catch (err) {
    console.log("[transcript] youtranscript failed:", (err as Error).message);
  }

  // Strategy 4: YouTube page scraping (last resort, fragile)
  return await fetchViaYouTubePage(videoId);
}

/* ─────────────────────────────────────────────
   Strategy 1 & 2: yt-dlp subtitle extraction
   ───────────────────────────────────────────── */

/**
 * Language fallback chain for subtitle selection.
 * Try one language at a time to avoid rate limiting.
 * English variants first, then common languages, then catch-all.
 */
const SUB_LANG_ATTEMPTS = [
  "en",
  "en-US",
  "en-GB",
  "de",
  "fr",
  "es",
  ".*", // catch-all for any available language
];

async function fetchViaYtDlp(
  videoId: string,
  useAndroid: boolean
): Promise<TranscriptSegment[]> {
  const url = `https://www.youtube.com/watch?v=${videoId}`;

  // Try each language one at a time to avoid rate limits
  for (const lang of SUB_LANG_ATTEMPTS) {
    try {
      return await tryYtDlpWithLang(videoId, url, lang, useAndroid);
    } catch (err) {
      // If this was a genuine "no captions" error, skip to next language
      const msg = (err as Error).message;
      if (msg.includes("No captions") || msg.includes("has no subtitles")) {
        continue;
      }
      // For rate limits and other transient errors, also try next
      if (msg.includes("429") || msg.includes("Too Many Requests")) {
        // Add a small delay before retrying
        await new Promise((r) => setTimeout(r, 1000));
        continue;
      }
      // For other errors, re-throw to let the caller try next strategy
      throw err;
    }
  }

  throw new Error("No captions available for this video in any language.");
}

async function tryYtDlpWithLang(
  videoId: string,
  url: string,
  lang: string,
  useAndroid: boolean
): Promise<TranscriptSegment[]> {
  const tmpDir = os.tmpdir();
  const outputBase = path.join(tmpDir, `clipflow_${videoId}`);

  const args = [
    "--skip-download",
    "--write-auto-subs",       // auto-generated captions
    "--write-subs",            // manual captions too
    "--sub-format", "srt",
    "--sub-lang", lang,
    "-o", outputBase,
    "--no-warnings",
  ];

  if (useAndroid) {
    args.push("--extractor-args", "youtube:player_client=android");
  }

  args.push(url);

  const { exitCode, stderr } = await spawnYtDlp(args);

  if (exitCode !== 0) {
    if (stderr.includes("no captions") || stderr.includes("has no subtitles")) {
      throw new Error("No captions available for this video.");
    }
    throw new Error(`yt-dlp exited with code ${exitCode}: ${stderr.slice(-200)}`);
  }

  // Find the generated SRT file
  const srtPath = await findSrtFile(outputBase, tmpDir, videoId);
  if (!srtPath) {
    throw new Error("No subtitle file was generated by yt-dlp.");
  }

  const content = await readFile(srtPath, "utf-8");

  // Clean up temp files
  await unlink(srtPath).catch(() => {});
  const tmpFiles = await readdir(tmpDir);
  for (const f of tmpFiles) {
    if (f.startsWith(`clipflow_${videoId}`)) {
      await unlink(path.join(tmpDir, f)).catch(() => {});
    }
  }

  if (!content || content.trim().length === 0) {
    throw new Error("Subtitle file is empty.");
  }

  const segments = parseSrt(content);
  if (segments.length === 0) {
    throw new Error("Could not extract any captions from subtitle file.");
  }

  return segments;
}

/**
 * Spawn yt-dlp as a child process and collect results.
 */
function spawnYtDlp(
  args: string[]
): Promise<{ stdout: string; stderr: string; exitCode: number }> {
  return new Promise((resolve, reject) => {
    const proc = spawn("yt-dlp", args, {
      stdio: ["ignore", "pipe", "pipe"],
      timeout: 45_000, // 45 second timeout
    });

    let stdout = "";
    let stderr = "";

    proc.stdout.on("data", (data: Buffer) => {
      stdout += data.toString();
    });

    proc.stderr.on("data", (data: Buffer) => {
      stderr += data.toString();
    });

    proc.on("error", (err) => {
      reject(new Error(`Failed to spawn yt-dlp: ${err.message}`));
    });

    proc.on("close", (code) => {
      resolve({
        stdout,
        stderr,
        exitCode: code ?? -1,
      });
    });
  });
}

/**
 * Find the SRT file generated by yt-dlp for a given video.
 * yt-dlp names output like: clipflow_VIDEOID.LANG.srt
 */
async function findSrtFile(
  outputBase: string,
  tmpDir: string,
  videoId: string
): Promise<string | null> {
  // First, try the direct path pattern yt-dlp uses
  // yt-dlp appends the subtitle language code before .srt
  const tmpFiles = await readdir(tmpDir);

  // Look for files matching: clipflow_<videoId>.*.srt
  const srtFiles = tmpFiles
    .filter((f) => f.startsWith(`clipflow_${videoId}`) && f.endsWith(".srt"))
    .sort((a, b) => {
      // Prefer English
      const aEn = a.includes(".en") ? 0 : 1;
      const bEn = b.includes(".en") ? 0 : 1;
      return aEn - bEn;
    });

  if (srtFiles.length > 0) {
    return path.join(tmpDir, srtFiles[0]);
  }

  return null;
}

/* ─────────────────────────────────────────────
   SRT Parser
   ───────────────────────────────────────────── */

/**
 * Parse SRT subtitle format into TranscriptSegment array.
 * Handles standard SRT with optional index numbers and millisecond timestamps.
 *
 * SRT format:
 *   1
 *   00:00:00,320 --> 00:00:14,580
 *   [Music]
 *
 *   2
 *   00:00:18,800 --> 00:00:25,960
 *   We're no strangers to
 */
function parseSrt(content: string): TranscriptSegment[] {
  const segments: TranscriptSegment[] = [];

  // Split on double newlines (blank line separates entries)
  const blocks = content.trim().split(/\n\s*\n/);

  for (const block of blocks) {
    // Each block: optional index number, timestamp line, one or more text lines
    const lines = block.trim().split("\n");
    if (lines.length < 2) continue;

    // Find the timestamp line (contains "-->")
    let timestampLineIdx = -1;
    for (let i = 0; i < lines.length; i++) {
      if (lines[i].includes("-->")) {
        timestampLineIdx = i;
        break;
      }
    }

    if (timestampLineIdx === -1) continue;

    const timeMatch = lines[timestampLineIdx].match(
      /(\d{1,2}):(\d{2}):(\d{2})[,.](\d{3})\s*-->\s*(\d{1,2}):(\d{2}):(\d{2})[,.](\d{3})/
    );
    if (!timeMatch) continue;

    const startHours = parseInt(timeMatch[1], 10);
    const startMins = parseInt(timeMatch[2], 10);
    const startSecs = parseInt(timeMatch[3], 10);
    const startMs = parseInt(timeMatch[4], 10);
    const endHours = parseInt(timeMatch[5], 10);
    const endMins = parseInt(timeMatch[6], 10);
    const endSecs = parseInt(timeMatch[7], 10);
    const endMs = parseInt(timeMatch[8], 10);

    const startTime = startHours * 3600 + startMins * 60 + startSecs + startMs / 1000;
    const endTime = endHours * 3600 + endMins * 60 + endSecs + endMs / 1000;
    const duration = Math.max(0, endTime - startTime);

    // Text is everything after the timestamp line
    const textLines = lines.slice(timestampLineIdx + 1);
    let text = textLines
      .join(" ")
      .replace(/<\/?[^>]+(>|$)/g, "") // strip HTML tags
      .replace(/&amp;/g, "&")
      .replace(/&lt;/g, "<")
      .replace(/&gt;/g, ">")
      .replace(/&quot;/g, '"')
      .replace(/&#39;/g, "'")
      .replace(/&apos;/g, "'")
      .replace(/&#(\d+);/g, (_, d) => String.fromCharCode(Number(d)))
      .replace(/\s+/g, " ")
      .trim();

    // Skip empty segments and music cues (but keep short ones that might be words)
    if (text.length === 0) continue;
    if (text === "[Music]" || text === "[music]" || text === "♪" || text === "♫") continue;
    if (text === "[Applause]" || text === "[applause]") continue;

    segments.push({
      text,
      start: Math.round(startTime * 100) / 100, // round to 2 decimal places
      duration: Math.round(duration * 100) / 100,
    });
  }

  if (segments.length === 0) {
    // Try alternate format: VTT-style (no index numbers, just timestamps)
    const vttRegex = /(\d{1,2}):(\d{2}):(\d{2})[,.](\d{3})\s*-->\s*(\d{1,2}):(\d{2}):(\d{2})[,.](\d{3})\s*\n([\s\S]*?)(?=\n\d{1,2}:\d{2}:\d{2}|\n*$)/g;
    let match;
    while ((match = vttRegex.exec(content)) !== null) {
      const startTime =
        parseInt(match[1]) * 3600 + parseInt(match[2]) * 60 + parseInt(match[3]) + parseInt(match[4]) / 1000;
      const endTime =
        parseInt(match[5]) * 3600 + parseInt(match[6]) * 60 + parseInt(match[7]) + parseInt(match[8]) / 1000;
      let text = match[9]
        .trim()
        .replace(/<\/?[^>]+(>|$)/g, "")
        .replace(/\s+/g, " ")
        .trim();

      if (text.length > 0 && text !== "[Music]" && text !== "[Applause]") {
        segments.push({
          text,
          start: Math.round(startTime * 100) / 100,
          duration: Math.round((endTime - startTime) * 100) / 100,
        });
      }
    }
  }

  return segments;
}

/* ─────────────────────────────────────────────
   Strategy 3: youtranscript.com API
   ───────────────────────────────────────────── */

async function fetchViaYouTranscript(
  videoId: string
): Promise<TranscriptSegment[]> {
  const resp = await fetch(
    `https://youtranscript.com/api/transcript?videoId=${videoId}`,
    { signal: AbortSignal.timeout(8_000) }
  );

  if (!resp.ok) {
    throw new Error(`youtranscript returned ${resp.status}`);
  }

  const data = (await resp.json()) as Record<string, unknown>;

  if (!Array.isArray(data.transcript) || data.transcript.length === 0) {
    throw new Error("youtranscript returned empty transcript");
  }

  const segs = data.transcript as Array<Record<string, unknown>>;
  return segs.map((seg) => ({
    text: typeof seg.text === "string" ? seg.text : "",
    start: typeof seg.offset === "number" ? seg.offset : 0,
    duration: typeof seg.duration === "number" ? seg.duration : 1,
  }));
}

/* ─────────────────────────────────────────────
   Strategy 4: YouTube page scraping (last resort)
   ───────────────────────────────────────────── */

async function fetchViaYouTubePage(
  videoId: string
): Promise<TranscriptSegment[]> {
  const resp = await fetch(`https://www.youtube.com/watch?v=${videoId}`, {
    headers: {
      "User-Agent":
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
      "Accept-Language": "en-US,en;q=0.9",
    },
    signal: AbortSignal.timeout(15_000),
  });

  if (!resp.ok) {
    throw new Error("Could not reach YouTube. Try again later.");
  }

  const html = await resp.text();

  // Extract ytInitialPlayerResponse JSON
  const playerMatch = html.match(/ytInitialPlayerResponse\s*=\s*(\{.+?\});/);
  if (!playerMatch) {
    throw new Error("Could not extract video data from YouTube page.");
  }

  let playerResponse: Record<string, unknown>;
  try {
    playerResponse = JSON.parse(playerMatch[1]);
  } catch {
    throw new Error("Failed to parse YouTube page data.");
  }

  const captions = (playerResponse.captions as Record<string, unknown>)
    ?.playerCaptionsTracklistRenderer as Record<string, unknown> | undefined;

  if (!captions) {
    throw new Error("No transcript available — this video has no captions.");
  }

  const captionTracks = captions.captionTracks as Array<Record<string, unknown>> | undefined;
  if (!captionTracks || captionTracks.length === 0) {
    throw new Error("No transcript available — captions are disabled.");
  }

  // Prefer English, fall back to first available
  const track =
    captionTracks.find(
      (t) =>
        t.languageCode === "en" ||
        (typeof t.languageCode === "string" && t.languageCode.startsWith("en"))
    ) || captionTracks[0];

  const baseUrl = track.baseUrl as string;
  if (!baseUrl) {
    throw new Error("No captions URL found.");
  }

  const captionsResp = await fetch(baseUrl);
  if (!captionsResp.ok) {
    throw new Error("Failed to download captions.");
  }

  const xml = await captionsResp.text();
  return parseTimedText(xml);
}

/**
 * Parse YouTube timedtext XML format into TranscriptSegment array.
 * Handles both <text> and <p> element formats.
 */
function parseTimedText(xml: string): TranscriptSegment[] {
  const segments: TranscriptSegment[] = [];

  // Format 1: <text start="..." dur="...">...</text>
  const textRegex = /<text\s+start="([\d.]+)"\s+dur="([\d.]+)"[^>]*>(.*?)<\/text>/g;
  let match: RegExpExecArray | null;
  while ((match = textRegex.exec(xml)) !== null) {
    let text = decodeXmlEntities(match[3]).trim();
    if (text.length > 0) {
      segments.push({
        text,
        start: parseFloat(match[1]),
        duration: parseFloat(match[2]),
      });
    }
  }

  // Format 2: <p t="..." d="...">...</p>
  if (segments.length === 0) {
    const pRegex = /<p\s+t="([\d.]+)"\s+d="([\d.]+)"[^>]*>(.*?)<\/p>/g;
    while ((match = pRegex.exec(xml)) !== null) {
      let text = decodeXmlEntities(match[3]).trim();
      if (text.length > 0) {
        segments.push({
          text,
          start: parseFloat(match[1]),
          duration: parseFloat(match[2]),
        });
      }
    }
  }

  if (segments.length === 0) {
    throw new Error("No transcript available — could not parse captions format.");
  }

  return segments;
}

function decodeXmlEntities(str: string): string {
  return str
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/<\/?[^>]+(>|$)/g, "") // strip HTML tags
    .replace(/&#(\d+);/g, (_, d) => String.fromCharCode(Number(d)));
}
